osx_image: xcode8.3

dist: trusty
sudo: true

language: node_js
node_js: "lts/*"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_script:
  - npm update @suen/music-api
  
script:
  - node build

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*
  skip_cleanup: true
  on:
    branch: ci-test
    tags: true

branches:
  only:
  - master
  - dev
  - ci-test
  
notifications:
  email: false